### ISSUE TITLE
Missing key(s) in state_dict: "encoder.loudness_extractor.smoothing_window"

### ISSUE THREAD

**Issue by andyjhj** [sweetcocoa/ddsp-pytorch#1]
When i try to inference the audio file with pretrained weights (provided by the weights.zip in branch models), some errors happened as following:
Traceback (most recent call last):
    net.load_state_dict(model)
.......
TrntimeError: Error(s) in loading state_dict for AutoEncoder:
    Missing key(s) in state_dict: "encoder.loudness_extractor.smoothing_window"

The pretrained weights  may be incomplete. Could you plz provide the complete ones? Thanks a lot.

**Comment by sweetcocoa** [comment]
Strange. As you said, it is right that the weight file I provided is missing the weight of the ```smoothing_window```. But in my environment, the problem you said is not reproduced. In fact, ```smoothing_window``` does not need any pretrained weights. 

Investigating this problem, I found an interesting fact, in Pytorch(1.4.0 and 1.5.1), when the ```nn.Parameter``` object is moved to the cuda device, it turns into a ```torch.Tensor``` object. from this point, ```smoothing_window``` is not a ```nn.Parameter```, but a ```Tensor```. so it does not need any weights. so I got no errors.

Did you modify any parts of the code? (e.g., ```.to.(device)``` ... )

```smoothing_window``` is not learnable parameter. theoretically, it does not need any pretrained weights. so it works the same even if you change it to ```Tensor```. here is the code of ```loudness_extractor```. : [loudness_extractor](https://github.com/sweetcocoa/ddsp-pytorch/blob/master/components/loudness_extractor.py) 

I believe that it works when you modify 30th line to this.

```python
        #self.smoothing_window = nn.Parameter(torch.hann_window(self.n_fft, dtype = torch.float32), requires_grad = False)
        self.smoothing_window = torch.hann_window(self.n_fft, dtype = torch.float32).to(self.device)
```
